# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1417, 845)
        MainWindow.setStyleSheet("background-color: rgb(28, 46, 61);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 111, 31))
        self.label.setObjectName("label")
        self.inputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.inputText.setGeometry(QtCore.QRect(480, 110, 341, 531))
        self.inputText.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.inputText.setObjectName("inputText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 50, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1110, 0, 81, 31))
        self.label_3.setObjectName("label_3")
        self.uploadTxt = QtWidgets.QPushButton(self.centralwidget)
        self.uploadTxt.setGeometry(QtCore.QRect(510, 680, 291, 41))
        self.uploadTxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.uploadTxt.setObjectName("uploadTxt")
        self.exportTxt = QtWidgets.QPushButton(self.centralwidget)
        self.exportTxt.setGeometry(QtCore.QRect(1020, 690, 241, 41))
        self.exportTxt.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.exportTxt.setObjectName("exportTxt")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(20, 110, 421, 531))
        self.plainTextEdit_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.labelRedireccion = QtWidgets.QLabel(self.centralwidget)
        self.labelRedireccion.setGeometry(QtCore.QRect(140, 690, 151, 31))
        self.labelRedireccion.setOpenExternalLinks(True)
        self.labelRedireccion.setObjectName("labelRedireccion")
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setGeometry(QtCore.QRect(860, 110, 521, 531))
        self.tabla.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(4)
        self.tabla.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tabla.setHorizontalHeaderItem(3, item)
        self.tabla.horizontalHeader().setDefaultSectionSize(125)
        self.tipo = QtWidgets.QLabel(self.centralwidget)
        self.tipo.setGeometry(QtCore.QRect(900, 60, 461, 31))
        self.tipo.setObjectName("tipo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1417, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Gramatica</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Entrada </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Salida</span></p></body></html>"))
        self.uploadTxt.setText(_translate("MainWindow", "Subir Archivo (mantenimiento)"))
        self.exportTxt.setText(_translate("MainWindow", "Exportar Salida Sintactica"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "S -> REMITENTE “P” Password  “A” ASUNTO “D” DESTINATARIO “T” TIPOMENSAJE\n"
"\n"
"REMITENTE: Correo\n"
"\n"
"ASUNTO: Letras Transformacion2|  Numeros Transformacion2\n"
"\n"
"DESTINATARIO: Correo\n"
"\n"
"Password : Letras  restoPass| Numeros restoPass| Caracteres restoPass \n"
"\n"
"restoPass:  Letras  restoPass| Numeros restoPass| Caracteres restoPass |ε\n"
"\n"
"TIPOMENSAJE: BN binarioNumero |MB mensajeBinario  | NB numeroBinario\n"
"\n"
"Caracteres: % | $ | # | ? |- |+ | . | ; | _ | ! \n"
"\n"
"Correo: Usuario @ Dominio . Tipo\n"
"\n"
"Usuario: Letras restoID | Numeros restoID\n"
"\n"
"restoID: Letras restoID | _ restoID |\n"
"Numeros restoID |. restoID | ε\n"
"\n"
"Dominio: outlook | gmail | hotmail | yahoo //HACER ESTE\n"
"\n"
"Tipo : mx | com \n"
"\n"
"Letras : a…z | A…Z\n"
"\n"
"Numeros: 0..9\n"
"\n"
"binarioNumero : Letras transformacion| b transformacion | Numeros transformacion\n"
"\n"
"transformacion: Letras transformacion |b transformacion | Numeros transformacion| ɛ \n"
"\n"
"mensajeBinario: Letras transformacion2 | Numeros transformacion2\n"
"\n"
"transformacion2:Letras tran sfomacion2 | Numeros transformacion2| ɛ \n"
"\n"
"numeroBinario:  Letras transformacion2| Numeros transformacion2\n"
"\n"
"b : 1 | 0 \n"
""))
        self.labelRedireccion.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Tabla Analisis</span></p></body></html>"))
        item = self.tabla.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tipo De Error"))
        item = self.tabla.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Linea"))
        item = self.tabla.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Posicion"))
        item = self.tabla.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Simbolo"))
        self.tipo.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
