
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightPADTrightBNrightMBrightNBA ARROBA B BN CARACTERES D DIGITOS DOMINIO GUIONBAJO LETRAS MB NB P PUNTO T TIPOS : Remitente P PasswordRemitente : CorreoAsunto : Letras transformacion2\n                | Numeros transformacion2Destinatario : Correo Password : Letras restoPass\n\t\t\t\t| Numeros restoPass\n\t\t\t\t| Caracteres restoPass restoPass : Letras restoPass\n\t\t\t\t| Numeros restoPass\n\t\t\t\t| Caracteres restoPass\n\t\t\t\t| empty tipoMensaje : empty binarioNumero\n                | empty mensajeBinario\n                | empty numeroBinarioCaracteres : CARACTERESCorreo : Usuario ARROBA Dominio PUNTO TipoUsuario : Letras restoID\n                | Numeros restoID restoID : Letras restoID\n                | GUIONBAJO restoID\n                | Numeros restoID\n                | PUNTO restoID\n                | empty Dominio : DOMINIO Tipo : TIPO Letras : LETRAS Numeros : DIGITOS transformacion : Letras transformacion\n                | B transformacion\n                | Numeros transformacion\n                | empty transformacion2 : Letras transformacion2\n                | Numeros transformacion2\n                | empty binarioNumero : Letras transformacion\n                | B transformacion\n                | Numeros transformacion mensajeBinario : Letras transformacion2\n                | Numeros transformacion2 numeroBinario : Letras transformacion2\n                | Numeros transformacion2 empty :'
    
_lr_action_items = {'LETRAS':([0,5,6,7,8,9,11,13,14,15,19,20,21,22,29,31,32,],[7,7,7,-27,-28,7,7,7,7,7,7,7,7,-16,7,7,7,]),'DIGITOS':([0,5,6,7,8,9,11,13,14,15,19,20,21,22,29,31,32,],[8,8,8,-27,-28,8,8,8,8,8,8,8,8,-16,8,8,8,]),'$end':([1,7,8,18,19,20,21,22,29,30,31,32,33,34,35,37,38,39,],[0,-27,-28,-1,-43,-43,-43,-16,-43,-6,-43,-43,-12,-7,-8,-9,-10,-11,]),'P':([2,3,40,41,],[9,-2,-17,-26,]),'ARROBA':([4,5,6,7,8,11,12,13,14,15,16,17,25,26,27,28,],[10,-43,-43,-27,-28,-43,-18,-43,-43,-43,-24,-19,-20,-21,-22,-23,]),'GUIONBAJO':([5,6,7,8,11,13,14,15,],[13,13,-27,-28,13,13,13,13,]),'PUNTO':([5,6,7,8,11,13,14,15,23,24,],[15,15,-27,-28,15,15,15,15,36,-25,]),'CARACTERES':([7,8,9,19,20,21,22,29,31,32,],[-27,-28,22,22,22,22,-16,22,22,22,]),'DOMINIO':([10,],[24,]),'TIPO':([36,],[41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Remitente':([0,],[2,]),'Correo':([0,],[3,]),'Usuario':([0,],[4,]),'Letras':([0,5,6,9,11,13,14,15,19,20,21,29,31,32,],[5,11,11,19,11,11,11,11,29,29,29,29,29,29,]),'Numeros':([0,5,6,9,11,13,14,15,19,20,21,29,31,32,],[6,14,14,20,14,14,14,14,31,31,31,31,31,31,]),'restoID':([5,6,11,13,14,15,],[12,17,25,26,27,28,]),'empty':([5,6,11,13,14,15,19,20,21,29,31,32,],[16,16,16,16,16,16,33,33,33,33,33,33,]),'Password':([9,],[18,]),'Caracteres':([9,19,20,21,29,31,32,],[21,32,32,32,32,32,32,]),'Dominio':([10,],[23,]),'restoPass':([19,20,21,29,31,32,],[30,34,35,37,38,39,]),'Tipo':([36,],[40,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Remitente P Password','S',3,'p_S','sintactico.py',12),
  ('Remitente -> Correo','Remitente',1,'p_Remitente','sintactico.py',16),
  ('Asunto -> Letras transformacion2','Asunto',2,'p_Asunto','sintactico.py',19),
  ('Asunto -> Numeros transformacion2','Asunto',2,'p_Asunto','sintactico.py',20),
  ('Destinatario -> Correo','Destinatario',1,'p_Destinatario','sintactico.py',24),
  ('Password -> Letras restoPass','Password',2,'p_Password','sintactico.py',27),
  ('Password -> Numeros restoPass','Password',2,'p_Password','sintactico.py',28),
  ('Password -> Caracteres restoPass','Password',2,'p_Password','sintactico.py',29),
  ('restoPass -> Letras restoPass','restoPass',2,'p_restoPass','sintactico.py',34),
  ('restoPass -> Numeros restoPass','restoPass',2,'p_restoPass','sintactico.py',35),
  ('restoPass -> Caracteres restoPass','restoPass',2,'p_restoPass','sintactico.py',36),
  ('restoPass -> empty','restoPass',1,'p_restoPass','sintactico.py',37),
  ('tipoMensaje -> empty binarioNumero','tipoMensaje',2,'p_tipoMensaje','sintactico.py',40),
  ('tipoMensaje -> empty mensajeBinario','tipoMensaje',2,'p_tipoMensaje','sintactico.py',41),
  ('tipoMensaje -> empty numeroBinario','tipoMensaje',2,'p_tipoMensaje','sintactico.py',42),
  ('Caracteres -> CARACTERES','Caracteres',1,'p_Caracteres','sintactico.py',45),
  ('Correo -> Usuario ARROBA Dominio PUNTO Tipo','Correo',5,'p_Correo','sintactico.py',48),
  ('Usuario -> Letras restoID','Usuario',2,'p_Usuario','sintactico.py',52),
  ('Usuario -> Numeros restoID','Usuario',2,'p_Usuario','sintactico.py',53),
  ('restoID -> Letras restoID','restoID',2,'p_restoID','sintactico.py',56),
  ('restoID -> GUIONBAJO restoID','restoID',2,'p_restoID','sintactico.py',57),
  ('restoID -> Numeros restoID','restoID',2,'p_restoID','sintactico.py',58),
  ('restoID -> PUNTO restoID','restoID',2,'p_restoID','sintactico.py',59),
  ('restoID -> empty','restoID',1,'p_restoID','sintactico.py',60),
  ('Dominio -> DOMINIO','Dominio',1,'p_Dominio','sintactico.py',63),
  ('Tipo -> TIPO','Tipo',1,'p_Tipo','sintactico.py',66),
  ('Letras -> LETRAS','Letras',1,'p_Letras','sintactico.py',69),
  ('Numeros -> DIGITOS','Numeros',1,'p_Numeros','sintactico.py',72),
  ('transformacion -> Letras transformacion','transformacion',2,'p_transformacion','sintactico.py',75),
  ('transformacion -> B transformacion','transformacion',2,'p_transformacion','sintactico.py',76),
  ('transformacion -> Numeros transformacion','transformacion',2,'p_transformacion','sintactico.py',77),
  ('transformacion -> empty','transformacion',1,'p_transformacion','sintactico.py',78),
  ('transformacion2 -> Letras transformacion2','transformacion2',2,'p_transformacion2','sintactico.py',81),
  ('transformacion2 -> Numeros transformacion2','transformacion2',2,'p_transformacion2','sintactico.py',82),
  ('transformacion2 -> empty','transformacion2',1,'p_transformacion2','sintactico.py',83),
  ('binarioNumero -> Letras transformacion','binarioNumero',2,'p_binarioNumero','sintactico.py',86),
  ('binarioNumero -> B transformacion','binarioNumero',2,'p_binarioNumero','sintactico.py',87),
  ('binarioNumero -> Numeros transformacion','binarioNumero',2,'p_binarioNumero','sintactico.py',88),
  ('mensajeBinario -> Letras transformacion2','mensajeBinario',2,'p_mensajeBinario','sintactico.py',91),
  ('mensajeBinario -> Numeros transformacion2','mensajeBinario',2,'p_mensajeBinario','sintactico.py',92),
  ('numeroBinario -> Letras transformacion2','numeroBinario',2,'p_numeroBinario','sintactico.py',95),
  ('numeroBinario -> Numeros transformacion2','numeroBinario',2,'p_numeroBinario','sintactico.py',96),
  ('empty -> <empty>','empty',0,'p_empty','sintactico.py',99),
]
